version: '3.8'

services:
  dev-db:
    image: postgres:13
    port:
      - 6500:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass123
      POSTGRES_DB: mydb
    networks:
      - nemosletter
networks:
  nemosletter:
